
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVERAGE CALCULATE CREATE EVEN FILTER FROM GREATER LIST NUMBER ODD PRINT RESULT SUM TOstatement : CREATE LIST FROM NUMBER TO NUMBERstatement : FILTER EVENstatement : FILTER ODDstatement : CALCULATE SUMstatement : PRINT RESULTstatement : PRINT LISTstatement : CALCULATE AVERAGEstatement : FILTER GREATER NUMBER'
    
_lr_action_items = {'CREATE':([0,],[2,]),'FILTER':([0,],[3,]),'CALCULATE':([0,],[4,]),'PRINT':([0,],[5,]),'$end':([1,7,8,10,11,12,13,15,18,],[0,-2,-3,-4,-7,-5,-6,-8,-1,]),'LIST':([2,5,],[6,13,]),'EVEN':([3,],[7,]),'ODD':([3,],[8,]),'GREATER':([3,],[9,]),'SUM':([4,],[10,]),'AVERAGE':([4,],[11,]),'RESULT':([5,],[12,]),'FROM':([6,],[14,]),'NUMBER':([9,14,17,],[15,16,18,]),'TO':([16,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> CREATE LIST FROM NUMBER TO NUMBER','statement',6,'p_create_list','parser.py',7),
  ('statement -> FILTER EVEN','statement',2,'p_filter_even','parser.py',11),
  ('statement -> FILTER ODD','statement',2,'p_filter_odd','parser.py',15),
  ('statement -> CALCULATE SUM','statement',2,'p_calculate_sum','parser.py',19),
  ('statement -> PRINT RESULT','statement',2,'p_print_result','parser.py',23),
  ('statement -> PRINT LIST','statement',2,'p_print_list','parser.py',29),
  ('statement -> CALCULATE AVERAGE','statement',2,'p_calculate_average','parser.py',33),
  ('statement -> FILTER GREATER NUMBER','statement',3,'p_filter_greater','parser.py',37),
]
